### ISSUE TITLE
CallTreeNode.getTreeDisplay throws an exception when trying to print certain contract addresses

### ISSUE THREAD

**Issue by mattdf** [ApeWorX/evm-trace#27]
### Environment information

* Python Version: 3.10.6
* OS: ubuntu 22.04
* evm_trace Version: 0.1.0a12

### What went wrong?

When printing out traces, if a contract called to an address that can't be normalized by `to_checksum_address` in `eth_utils`, an exception gets thrown, but this shouldn't happen because it's valid for contracts to attempt to call into nonsense addresses like `0x01` that can't be normalized:

```
Traceback (most recent call last):
  File "<snip>/main.py", line 81, in <module>
    print(trace)
  File "<snip>/venv/lib/python3.10/site-packages/evm_trace/base.py", line 37, in __str__
    return get_tree_display(self)
  File "<snip>/venv/lib/python3.10/site-packages/evm_trace/display.py", line 10, in get_tree_display
    return "\n".join([str(t) for t in TreeRepresentation.make_tree(call)])
  File "<snip>/venv/lib/python3.10/site-packages/evm_trace/display.py", line 10, in <listcomp>
    return "\n".join([str(t) for t in TreeRepresentation.make_tree(call)])
  File "<snip>/venv/lib/python3.10/site-packages/evm_trace/display.py", line 86, in __str__
    parts = [f"{filename_prefix} {self.title}"]
  File "<snip>/venv/lib/python3.10/site-packages/evm_trace/display.py", line 39, in title
    address = to_checksum_address(address_hex_str) if address_hex_str else None
  File "<snip>/venv/lib/python3.10/site-packages/eth_utils/address.py", line 112, in to_checksum_address
    norm_address = to_normalized_address(value)
  File "<snip>/venv/lib/python3.10/site-packages/eth_utils/address.py", line 63, in to_normalized_address
    raise ValueError(
ValueError: Unknown format '0x01', attempted to normalize to '0x01'

Process finished with exit code 1
```

### How can it be fixed?

The exception should be caught inside `TreeRepresentation.title` and ignored, as is done in the `ImportError` case.

**Comment by unparalleled-js** [comment]
fixed!
