### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object [APE-1192]

### ISSUE THREAD

**Issue by JONEmoad** [ApeWorX/evm-trace#45]
### Environment information

Ubuntu 22
- Python Version:  3.10.6
- evm-trace version: https://github.com/ApeWorX/evm-trace/releases/tag/v0.1.0-alpha.21
- ape version: 0.6.13

- full output of the error you received
```
python3 debug_trace.py
Traceback (most recent call last):
  File "/home/dev/trace/debug_trace.py", line 35, in <module>
    calltree = get_calltree_from_geth_trace(frames, **root_node_kwargs)
  File "/home/dev/trace/venvape/lib/python3.10/site-packages/evm_trace-0.1.0a21-py3.10.egg/evm_trace/geth.py", line 103, in get_calltree_from_geth_trace
    return _create_node(
  File "/home/dev/trace/venvape/lib/python3.10/site-packages/evm_trace-0.1.0a21-py3.10.egg/evm_trace/geth.py", line 228, in _create_node
    subcall = _create_node(trace=trace, show_internal=show_internal, **data)
  File "/home/dev/trace/venvape/lib/python3.10/site-packages/evm_trace-0.1.0a21-py3.10.egg/evm_trace/geth.py", line 228, in _create_node
    subcall = _create_node(trace=trace, show_internal=show_internal, **data)
  File "/home/dev/trace/venvape/lib/python3.10/site-packages/evm_trace-0.1.0a21-py3.10.egg/evm_trace/geth.py", line 228, in _create_node
    subcall = _create_node(trace=trace, show_internal=show_internal, **data)
  [Previous line repeated 988 more times]
  File "/home/dev/trace/venvape/lib/python3.10/site-packages/evm_trace-0.1.0a21-py3.10.egg/evm_trace/geth.py", line 220, in _create_node
    data = create_call_node_data(frame)
  File "/home/dev/trace/venvape/lib/python3.10/site-packages/evm_trace-0.1.0a21-py3.10.egg/evm_trace/geth.py", line 121, in create_call_node_data
    data: Dict = {"address": frame.address, "depth": frame.depth}
  File "/home/dev/trace/venvape/lib/python3.10/site-packages/evm_trace-0.1.0a21-py3.10.egg/evm_trace/geth.py", line 60, in address
    return HexBytes(self.stack[-2][-20:])
  File "/home/dev/trace/venvape/lib/python3.10/site-packages/hexbytes/main.py", line 68, in __getitem__
    return type(self)(result)
  File "/home/dev/trace/venvape/lib/python3.10/site-packages/hexbytes/main.py", line 42, in __new__
    bytesval = to_bytes(val)
  File "/home/dev/trace/venvape/lib/python3.10/site-packages/hexbytes/_utils.py", line 14, in to_bytes
    if isinstance(val, bytes):
RecursionError: maximum recursion depth exceeded while calling a Python object
```

-full code:

```
from web3 import HTTPProvider, Web3
from evm_trace import TraceFrame, CallType, get_calltree_from_geth_trace

web3 = Web3(HTTPProvider("quiknode"))

txn_hash = "0x" # any Transaction etherum
#struct_logs = web3.manager.request_blocking("debug_traceTransaction", [txn_hash]).structLogs
trace_dump = web3.manager.request_blocking("debug_traceTransaction", [txn_hash], {"enableMemory": True, "enableReturnData": True})
struct_logs = trace_dump["structLogs"]

frames = [TraceFrame.parse_obj(item) for item in struct_logs]
tx = web3.eth.get_transaction(txn_hash)

root_node_kwargs = {
"gas_cost": tx["gas"],
"address": tx["to"],
"calldata": tx.get("input", ""),
"call_type": CallType.CALL,
}

calltree = get_calltree_from_geth_trace(frames, **root_node_kwargs)
```

**Comment by antazoey** [comment]
Which node are you using?

**Comment by antazoey** [comment]
the line that starts with `trace_dump = ` has a small mistaken, the dict should be in the list in the arguments and not as a separate argument, like this:

```python
trace_dump = web3.manager.request_blocking("debug_traceTransaction", [txn_hash, {"enableMemory": True, "enableReturnData": True}])
```
